# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duck < Formula
  desc "P2P Chat"
  homepage "https://github.com/dripverse/duck"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DripVerse/duck/releases/download/v1.2.0/duck_Darwin_arm64.tar.gz"
      sha256 "f4388d5b776fef176c1382410e1d09028ecd2796eef9d7e35178a103dc600097"

      def install
        bin.install "duck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DripVerse/duck/releases/download/v1.2.0/duck_Darwin_x86_64.tar.gz"
      sha256 "0a7c77a3b42fef22b69cbf7bf929afde42d9402adccf35eb71e920ad0538c739"

      def install
        bin.install "duck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DripVerse/duck/releases/download/v1.2.0/duck_Linux_arm64.tar.gz"
      sha256 "943e3a8750dcd59e5889fd403f557e71550bedaa30c34523f812a5851b6173db"

      def install
        bin.install "duck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DripVerse/duck/releases/download/v1.2.0/duck_Linux_x86_64.tar.gz"
      sha256 "b08db9c7a6857c8d4f658eefb3d7a1a75fc62af8bdc2c7d93447b69b7bbaa47e"

      def install
        bin.install "duck"
      end
    end
  end
end
