# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duck < Formula
  desc "P2P Chat"
  homepage "https://github.com/dripverse/duck"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DripVerse/duck/releases/download/v1.1.0/duck_Darwin_x86_64.tar.gz"
      sha256 "367b56c3ce93d9e868dbb1e4b08a4259ac40095a0ae0c2dbc243538291d6db27"

      def install
        bin.install "duck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DripVerse/duck/releases/download/v1.1.0/duck_Darwin_arm64.tar.gz"
      sha256 "db7d6e31a6d48b1a63e5fe9882eca06d138465bee4b0b3b5d50d1a7482352f92"

      def install
        bin.install "duck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DripVerse/duck/releases/download/v1.1.0/duck_Linux_arm64.tar.gz"
      sha256 "d5c3f1a2fc8e8ed54641a1a06d7b1c547a62730a83e9dfa8887be7ac628ce452"

      def install
        bin.install "duck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DripVerse/duck/releases/download/v1.1.0/duck_Linux_x86_64.tar.gz"
      sha256 "a31432f294fcdf5c44767db250c73f1fc2f16f484bb5109c38f68d9661683b27"

      def install
        bin.install "duck"
      end
    end
  end
end
